name: docs

on: 
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs:
    runs-on: ubuntu-latest
    name: build up document and deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install sphinx and manim env
      run: |
        python3 -m pip install --upgrade pip
        sudo apt-get update
        sudo apt-get install -y python3-setuptools libpango1.0-dev
        # Pin Jinja2 before installing other requirements to avoid import error
        python3 -m pip install "Jinja2<3.1"
        python3 -m pip install -r docs/requirements.txt
        python3 -m pip install -r requirements.txt

    - name: Build document with Sphinx
      run: |
        cd docs
        export PATH="$PATH:/home/runner/.local/bin"
        export SPHINXBUILD="python3 -m sphinx"
        make html

    - name: Deploy to GitHub pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        ACCESS_TOKEN: ${{ secrets.DOC_DEPLOY_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
